//------------------------------------------------------------------------------------------------------------
//User Editable Configurable Value
const daysSinceLastActive = 365;
const archiveWorkspace = 'Enter id of archive workspace';
const testRun = true; 
const deleteEmptyWorkspaces = true; 

//------------------------------------------------------------------------------------------------------------
//REQUIRED authintication credentials
//These are the credentials required to authenticate with the the Trello API. 

const apiKey = 'API Key'; //Enter your personal API key
const apiToken = 'API Token'; //Enter your personal API token that was generated by the API key above
const enterpriseId = 'Enterprise ID'; //Enter the ID of the Trello Enterprise you want to add members to.

//------------------------------------------------------------------------------------------------------------
//Below this line is the main execution code. Edits below this line are not recommended unless you are trying to adapt the core funtionality of the script.

const fetch = require('node-fetch');
const moment = require('moment');
const fs = require('fs');
const headers = { 'Accept': 'application/json' };
const timestamp = moment().format("YYYY-MM-DD-HHmmss");


async function fetchWithTimeout(resource, options) {
  const { timeout = 50000 } = options;
  const controller = new AbortController();
  const id = setTimeout(() => controller.abort(), timeout);
  const response = await fetch(resource, { ...options, signal: controller.signal });
  clearTimeout(id);
  return response;
}

async function getAndMoveEnterpriseWorkspaces() {
  if (testRun == true) {console.log("TEST RUN MODE - Starting to analyze your Enterprise Workspaces")};
  console.log("Starting to analyze your Enterprise Workspaces");
  const getEnterpriseWorkspaceIDs = `https://api.trello.com/1/enterprises/${enterpriseId}?key=${apiKey}&token=${apiToken}`;

  fs.writeFileSync(`boards_report_${timestamp}.csv`, 'Workspace ID, Board ID, Board Name, Already Closed, Date Last View/Activity, Eligible To Be Closed\r\n');
  fs.writeFileSync(`workspace_report_${timestamp}.csv`, 'Workspace ID, Workspace Name, Member Count, Status\r\n');

  const response = await fetchWithTimeout(getEnterpriseWorkspaceIDs, { headers });
  if (!response.ok) throw new Error(`HTTP error - get enterprise workspaces! status: ${response.status}`);
  
  const body = await response.json();
  const workspaceResponse = body.idOrganizations;

  for (const organization of workspaceResponse) {
    await getBoardsOfEnterprise(organization);
  }

  const deletedWorkspaces = [];
  for (const organization of workspaceResponse) {
    const isDeleted = await checkIfWorkspaceEmpty(organization);
    if (isDeleted) {
      deletedWorkspaces.push(organization);
    }
  }

  for (const organization of workspaceResponse) {
    const isDeleted = deletedWorkspaces.includes(organization);
    fs.appendFileSync(`workspace_report_${timestamp}.csv`, [organization, , , isDeleted ? "Deleted" : "Not Deleted"].join(', ') + '\r\n');
  }
  console.log("All done!")
}

async function getBoardsOfEnterprise(workspaceId) {
  console.log(`Getting boards belonging to ${workspaceId} to see which to close/archive.`);
  const getAllBoardsOfEnterprise = `https://api.trello.com/1/organizations/${workspaceId}/boards?key=${apiKey}&token=${apiToken}`;
  
  const response = await fetchWithTimeout(getAllBoardsOfEnterprise, { headers });
  if (!response.ok) throw new Error(`HTTP error - get boards of enterprise! status: ${response.status}`);
  
  const boardResponse = await response.json();
  for (const board of boardResponse) {
    const daysSinceActive = moment().diff(moment(board.dateLastActivity), 'days');
    const eligible = ((daysSinceActive > daysSinceLastActive || isNaN(daysSinceActive)) && !board.closed) ? "Yes" : "No";

    if (eligible === "Yes") {
      const closeBoard = `https://api.trello.com/1/boards/${board.id}?closed=true&key=${apiKey}&token=${apiToken}`;
      if (testRun == false){
      const moveResponse = await fetchWithTimeout(closeBoard, { method: 'PUT',
        headers: headers })
      if (!moveResponse.ok) throw new Error(`HTTP error - close/archive board! status: ${moveResponse.status}`);;}
      console.log(`Closed/Archived ${board.id} board`);
    }
    
    fs.appendFileSync(`boards_report_${timestamp}.csv`, [workspaceId, board.id, board.name, board.closed, daysSinceActive, board.dateLastActivity, eligible].join(', ') + '\r\n');
  }
  moveBoardsOfEnterprise(workspaceId);
}

async function moveBoardsOfEnterprise(workspaceId) {
  console.log(`Getting boards belonging to ${workspaceId} see all boards are closed and if they should be moved to the Archive Workspace`);
  const getOpenBoardsOfEnterprise = `https://api.trello.com/1/organizations/${workspaceId}/boards?filter=open&key=${apiKey}&token=${apiToken}`;
  const openResponse = await fetchWithTimeout(getOpenBoardsOfEnterprise, { headers });
  const getAllBoardsOfEnterprise = `https://api.trello.com/1/organizations/${workspaceId}/boards?&key=${apiKey}&token=${apiToken}`;
  const response = await fetchWithTimeout(getAllBoardsOfEnterprise, { headers });
  if (!openResponse.ok) throw new Error(`HTTP error - get boards of enterprise! status: ${response.status}`);
  const openBoardResponse = await openResponse.json();
  const boardResponse = await response.json();
  if (openBoardResponse.length === 0) {
  for (const board of boardResponse) {
      const moveBoard = `https://api.trello.com/1/boards/${board.id}?idOrganization=${archiveWorkspace}&key=${apiKey}&token=${apiToken}`;
      if (testRun === false){
      const moveResponse = await fetchWithTimeout(moveBoard, { method: 'PUT',
        headers: headers });
      if (!moveResponse.ok) throw new Error(`HTTP error - move board! status: ${moveResponse.status}`);};
      console.log(`Moved ${board.id} board`);
  }
} 
}

async function checkIfWorkspaceEmpty(workspaceId) {
  console.log(`Checking if ${workspaceId} is empty`);
  const getOpenBoardsOfWorkspace = `https://api.trello.com/1/organizations/${workspaceId}/boards?filter=open&key=${apiKey}&token=${apiToken}`;
  
  const response = await fetchWithTimeout(getOpenBoardsOfWorkspace, { headers });
  if (!response.ok) throw new Error(`HTTP error - get open boards of workspace! status: ${response.status}`);
  
  const boardResponse = await response.json();
  const deleteWorkspace = `https://api.trello.com/1/organizations/${workspaceId}?key=${apiKey}&token=${apiToken}`;
  if (boardResponse.length === 0 && workspaceId != archiveWorkspace && deleteEmptyWorkspaces === true ) {
    if (testRun === false){
    const deleteResponse = await fetchWithTimeout(deleteWorkspace, { 
      method: 'Delete',
      headers: headers });
    if (!deleteResponse.ok) throw new Error(`HTTP error - deleting board! status: ${deleteResponse.status}`);};
    console.log(`${workspaceId} has been deleted.`);
    return true;  // Workspace was deleted.
  }
  return false;  // Workspace was not deleted.
}

getAndMoveEnterpriseWorkspaces();
